#!/usr/bin/env bash

# shellcheck disable=SC2086,SC2207

_globalprotect_completions() {
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD - 1]}"
  opts=()

  # Handle different contexts
  case "${prev}" in
    globalprotect | gp)
      opts=(collect-log connect disconnect import-certificate quit rediscover-network remove-user resubmit-hip set-log show status)
      ;;
    show)
      opts=(--details --error --help --host-state --manual-gateway --notification --ssl-only --statistics --status --version --welcome-page)
      ;;
    connect)
      opts=(--portal --gateway --username)
      ;;
    status)
      opts=(--json --verbose)
      ;;
  esac

  COMPREPLY=($(compgen -W "${opts[*]}" -- ${cur}))
}

# Register the completion function
complete -F _globalprotect_completions globalprotect
complete -F _globalprotect_completions gp
