# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$directory\
$python\
($git_branch)($git_status )\
$docker_context\
$golang\
$nodejs\
$cmd_duration\
$jobs\
$line_break\
((${custom.kshell_deployment})($azure)(${custom.postgres})($kubernetes)(${custom.https_proxy})\n)\
$status\
(${custom.kshell_active})\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname]($style):'
style = 'green'

[directory]
truncation_length = 9
truncate_to_repo = true
truncation_symbol = ''
format = " [$path]($style) "

# Azure and Kubernetes info restored
[azure]
disabled = false
format = '[$symbol$subscription ]($style)'
symbol = '󰠅 '
style = 'bold blue'

[kubernetes]
disabled = false
format = '[$symbol](bold yellow)[(:$namespace)](fg:#f5e042)'

[custom.kshell_active]
when = 'test -v KS_DIR && ! test -v KS_DEPLOYMENT'
style = 'fg:#eb34e8'
symbol = 'κ'
format = '[$symbol$output]($style)'

[custom.kshell_deployment]
when = 'test -v KS_DEPLOYMENT'
command = "echo -n $KS_DEPLOYMENT"
style = 'fg:#eb34e8'
symbol = '◈ '
format = '[$symbol$output ]($style)'

[custom.postgres]
when = 'test -v PGDATABASE'
command = "echo -n $PGDATABASE"
style = 'fg:#eeeeee'
symbol = '🐘 '
format = '[$symbol$output ]($style)'

[custom.https_proxy]
when = 'test -v HTTPS_PROXY'
style = 'fg:#eb34e8'
symbol = '⇄ '
format = '[$symbol$output ]($style)'

[custom.tmux_sync]
when = '[ -n "$TMUX" ]'
command = 'tmux-starship-sync &'
symbol = ' '

[profiles]
tmux_title = """
(${custom.kshell_active} )\
(${custom.kshell_deployment})($azure)(${custom.postgres})($kubernetes)(${custom.https_proxy})\
$directory\
$python\
($git_branch)($git_status )\
$golang\
"""
tmux_prompt = """
${custom.tmux_sync}\
$cmd_duration\
$jobs\
$status\
$character"""

[git_branch]
style = 'fg:green'
format = '[$symbol$branch ]($style)'
symbol = ' '

[git_status]
style = 'fg:red'
format = '[$all_status$ahead_behind]($style)'

[golang]
format = '[$symbol$version](bold cyan)'
symbol = '🐹 '

[shell]
disabled = false
format = '[$indicator]($style)'
bash_indicator = ''
zsh_indicator = 'ζ'
style = 'fg:#666666'

[character]
success_symbol = "[➜](bold green)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'

[package]
disabled = true

[fill]
symbol = ' '

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = '%T'
style = 'fg:#666666'
