[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
padding.x = 8
padding.y = 8
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
