[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
]

[env]
TERM = "xterm-256color"

[terminal]
shell.program = "/usr/local/bin/zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98
option_as_alt = "Both"
